# Generated by Django 3.0 on 2019-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191211_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='www.shopify.com', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='store',
            field=models.CharField(default='Shopify', max_length=100),
        ),
    ]
