# Generated by Django 3.0 on 2019-12-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191213_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(default='https://www.shopify.com/', max_length=300),
        ),
    ]
